spring:
  application:
    name: sping-boot-admin-websocket
  boot:
    admin:
      client:
        url: http://localhost:8000
        username: root
        password: root
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
        turbine:
          location: dj-atliwen-edi-admin
        discovery:
     #        ignored-services: turbine
          ignored-services: ss-erp-*,yjc-zhongjie,*jsp*,admin-discovery

server:
  port: 8002
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"