spring:
  application:
    name: spring-boot-admin-gateway
  security:
    user:
      name: root
      password: root
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://www.ityouknow.com
          predicates:
            - Path=/spring-cloud
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
server:
  port: 7000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
