spring:
  application:
    name: sping-boot-admin-mail
  security:
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  mail:
    host: smtp.163.com
    username: liujialin1106@163.com
    password: LIUjialintest
    default-encoding: UTF-8
server:
  port: 8001
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"